export const RECIPE_LOADED = 'RECIPE_LOADED';
export const HIGH_MARGIN_LOADED = 'HIGH_MARGIN_LOADED';
export const LOW_MARGIN_LOADED = 'LOW_MARGIN_LOADED';
export const HIGHT_FLUCTUATION_LOADED = 'HIGHT_FLUCTUATION_LOADED';